### ISSUE TITLE
merge operation of BlockWorldState

### ISSUE THREAD

**Issue by Lbqds** [khipu-io/khipu#1]
https://github.com/khipu-io/khipu/blob/27f8e69f830010a475435def14fe90227989bd81/khipu-eth/src/main/scala/khipu/ledger/BlockWorldState.scala#L336

there are two `laster.codes.contains(x)` here, one of them should be `laster.trieAccounts.logs.contains(x)`

**Comment by dcaoyuan** [comment]
Good spot. Fixed. Until official announce, all changes will be `git push -f`. Thanks
