### ISSUE TITLE
Fast sync is hard to find nodes and hangs at block 3004252.

### ISSUE THREAD

**Issue by hustnn** [khipu-io/khipu#3]
Take more than 15 minutes, still cannot connect to other nodes. Is it the network problem?

09:19:20 [peer] Discovered 638 nodes (290 dropped), handshaked 1/30  (in/out): (0/1). Connecting to 29 more nodes.
09:19:20 [fast] Block: 3004252/6219872, 0/s. State: 2091792/2105924, 0/s, 400 in working. Peers: (in/out) (0/1), (working/good/node/black) (1/0/0/1)
09:19:25 [fast] Block: 3004252/6219872, 0/s. State: 2091792/2105924, 0/s, 0 in working. Peers: (in/out) (0/1), (working/good/node/black) (0/0/0/1)
09:19:30 [fast] Block: 3004252/6219872, 0/s. State: 2091792/2105924, 0/s, 0 in working. Peers: (in/out) (0/1), (working/good/node/black) (0/0/0/1)
09:19:35 [fast] Block: 3004252/6219872, 0/s. State: 2091792/2105924, 0/s, 0 in working. Peers: (in/out) (0/1), (working/good/node/black) (0/0/0/1)
09:19:40 [peer] Discovered 638 nodes (290 dropped), handshaked 1/30  (in/out): (0/1). Connecting to 29 more nodes.
09:19:40 [fast] Block: 3004252/6219872, 0/s. State: 2091792/2105924, 0/s, 0 in working. Peers: (in/out) (0/1), (working/good/node/black) (0/0/0/1)
09:19:45 [fast] Block: 3004252/6219872, 0/s. State: 2091792/2105924, 0/s, 0 in working. Peers: (in/out) (0/1), (working/good/node/black) (0/0/0/1)
09:19:50 [fast] Block: 3004252/6219872, 0/s. State: 2091792/2105924, 0/s, 0 in working. Peers: (in/out) (0/1), (working/good/node/black) (0/0/0/1)
09:19:55 [fast] Block: 3004252/6219872, 0/s. State: 2091792/2105924, 0/s, 0 in working. Peers: (in/out) (0/1), (working/good/node/black) (0/0/0/1)
09:20:00 [peer] Discovered 638 nodes (290 dropped), handshaked 1/30  (in/out): (0/1). Connecting to 29 more nodes.
09:20:00 [fast] Block: 3004252/6219872, 0/s. State: 2091792/2105924, 0/s, 0 in working. Peers: (in/out) (0/1), (working/good/node/black) (0/0/0/1)
09:20:05 [fast] Block: 3004252/6219872, 0/s. State: 2091792/2105924, 0/s, 0 in working. Peers: (in/out) (0/1), (working/good/node/black) (0/0/0/1)
09:20:10 [fast] Block: 3004252/6219872, 0/s. State: 2091792/2105924, 0/s, 0 in working. Peers: (in/out) (0/1), (working/good/node/black) (0/0/0/1)
09:20:15 [fast] Block: 3004252/6219872, 0/s. State: 2091792/2105924, 0/s, 0 in working. Peers: (in/out) (0/1), (working/good/node/black) (0/0/0/1)
09:20:15 [fast] Saved sync state in 4 ms, best header number: 3004252, bodies queue: 0, receipts queue: 0, nodes queue: 14132, downloaded nodes: 2091792
09:20:20 [peer] Discovered 638 nodes (290 dropped), handshaked 1/30  (in/out): (0/1). Connecting to 29 more nodes.
09:20:20 [fast] Block: 3004252/6219872, 0/s. State: 2091792/2105924, 0/s, 0 in working. Peers: (in/out) (0/1), (working/good/node/black) (0/0/0/1)
09:20:25 [fast] Block: 3004252/6219872, 0/s. State: 2091792/2105924, 0/s, 0 in working. Peers: (in/out) (0/1), (working/good/node/black) (1/0/0/1)
09:20:30 [fast] Block: 3004252/6219872, 0/s. State: 2091792/2105924, 0/s, 0 in working. Peers: (in/out) (0/1), (working/good/node/black) (1/0/0/1)
09:20:35 [fast] Block: 3004252/6219872, 0/s. State: 2091792/2105924, 0/s, 0 in working. Peers: (in/out) (0/1), (working/good/node/black) (1/0/0/1)
09:20:40 [peer] Discovered 638 nodes (290 dropped), handshaked 1/30  (in/out): (0/1). Connecting to 29 more nodes.
09:20:40 [fast] Block: 3004252/6219872, 0/s. State: 2091792/2105924, 0/s, 0 in working. Peers: (in/out) (0/1), (working/good/node/black) (1/0/0/1)
09:20:45 [fast] Block: 3004252/6219872, 0/s. State: 2091792/2105924, 0/s, 0 in working. Peers: (in/out) (0/1), (working/good/node/black) (1/0/0/1)
09:20:50 [fast] Block: 3004252/6219872, 0/s. State: 2091792/2105924, 0/s, 0 in working. Peers: (in/out) (0/1), (working/good/node/black) (1/0/0/1)
09:20:55 [fast] Block: 3004252/6219872, 0/s. State: 2091792/2105924, 0/s, 0 in working. Peers: (in/out) (0/1), (working/good/node/black) (1/0/0/1)
09:21:00 [peer] Discovered 638 nodes (290 dropped), handshaked 1/30  (in/out): (0/1). Connecting to 29 more nodes.
09:21:00 [fast] Block: 3004252/6219872, 0/s. State: 2091792/2105924, 0/s, 0 in working. Peers: (in/out) (0/1), (working/good/node/black) (1/0/0/1)
09:21:05 [fast] Block: 3004252/6219872, 0/s. State: 2091792/2105924, 0/s, 0 in working. Peers: (in/out) (0/1), (working/good/node/black) (1/0/0/1)
09:21:10 [fast] Block: 3004252/6219872, 0/s. State: 2091792/2105924, 0/s, 0 in working. Peers: (in/out) (0/1), (working/good/node/black) (1/0/0/1)
09:21:15 [fast] Saved sync state in 3 ms, best header number: 3004252, bodies queue: 0, receipts queue: 0, nodes queue: 14132, downloaded nodes: 2091792
09:21:15 [fast] Block: 3004252/6219872, 0/s. State: 2091792/2105924, 0/s, 0 in working. Peers: (in/out) (0/1), (working/good/node/black) (1/1/0/0)
09:21:20 [peer] Discovered 638 nodes (290 dropped), handshaked 1/30  (in/out): (0/1). Connecting to 29 more nodes.
09:21:20 [fast] Block: 3004252/6219872, 0/s. State: 2091792/2105924, 0/s, 0 in working. Peers: (in/out) (0/1), (working/good/node/black) (1/1/0/0)
09:21:25 [fast] Block: 3004252/6219872, 0/s. State: 2091792/2105924, 0/s, 0 in working. Peers: (in/out) (0/1), (working/good/node/black) (0/0/0/1)
09:21:30 [fast] Block: 3004252/6219872, 0/s. State: 2091792/2105924, 0/s, 0 in working. Peers: (in/out) (0/1), (working/good/node/black) (0/0/0/1)
09:21:35 [fast] Block: 3004252/6219872, 0/s. State: 2091792/2105924, 0/s, 0 in working. Peers: (in/out) (0/1), (working/good/node/black) (0/0/0/1)
09:21:40 [peer] Discovered 638 nodes (290 dropped), handshaked 1/30  (in/out): (0/1). Connecting to 29 more nodes.
09:21:40 [fast] Block: 3004252/6219872, 0/s. State: 2091792/2105924, 0/s, 0 in working. Peers: (in/out) (0/1), (working/good/node/black) (0/0/0/1)
09:21:45 [fast] Block: 3004252/6219872, 0/s. State: 2091792/2105924, 0/s, 0 in working. Peers: (in/out) (0/1), (working/good/node/black) (0/0/0/1)
09:21:50 [fast] Block: 3004252/6219872, 0/s. State: 2091792/2105924, 0/s, 0 in working. Peers: (in/out) (0/1), (working/good/node/black) (0/0/0/1)
09:21:55 [fast] Block: 3004252/6219872, 0/s. State: 2091792/2105924, 0/s, 0 in working. Peers: (in/out) (0/1), (working/good/node/black) (0/0/0/1)
09:22:00 [peer] Discovered 638 nodes (290 dropped), handshaked 1/30  (in/out): (0/1). Connecting to 29 more nodes.
09:22:00 [fast] Block: 3004252/6219872, 0/s. State: 2091792/2105924, 0/s, 0 in working. Peers: (in/out) (0/1), (working/good/node/black) (0/0/0/1)
09:22:05 [fast] Block: 3004252/6219872, 0/s. State: 2091792/2105924, 0/s, 0 in working. Peers: (in/out) (0/1), (working/good/node/black) (0/0/0/1)
09:22:10 [fast] Block: 3004252/6219872, 0/s. State: 2091792/2105924, 0/s, 0 in working. Peers: (in/out) (0/1), (working/good/node/black) (0/0/0/1)
09:22:15 [fast] Block: 3004252/6219872, 0/s. State: 2091792/2105924, 0/s, 0 in working. Peers: (in/out) (0/1), (working/good/node/black) (0/0/0/1)
09:22:15 [fast] Saved sync state in 2 ms, best header number: 3004252, bodies queue: 0, receipts queue: 0, nodes queue: 14132, downloaded nodes: 2091792
09:22:20 [peer] Discovered 638 nodes (291 dropped), handshaked 1/30  (in/out): (0/1). Connecting to 29 more nodes.
09:22:20 [fast] Block: 3004252/6219872, 0/s. State: 2091792/2105924, 0/s, 0 in working. Peers: (in/out) (0/1), (working/good/node/black) (0/0/0/1)
09:22:25 [fast] Block: 3004252/6219872, 0/s. State: 2091792/2105924, 0/s, 0 in working. Peers: (in/out) (0/1), (working/good/node/black) (0/0/0/1)
09:22:30 [fast] Block: 3004252/6219872, 0/s. State: 2091792/2105924, 0/s, 0 in working. Peers: (in/out) (0/1), (working/good/node/black) (0/0/0/1)

**Comment by dcaoyuan** [comment]
Seem 3004252 is a common stuck position?
* https://github.com/input-output-hk/mantis/wiki/Client-fast-sync-testing
* and Google search result:
![screenshot from 2018-09-13 07-14-47](https://user-images.githubusercontent.com/271571/45493915-c1078000-b724-11e8-9d71-7ef6819b1c47.png)

**Comment by dcaoyuan** [comment]
May have been fixed by 01de9685

**Comment by hustnn** [comment]
@dcaoyuan Thanks. Will try.

**Comment by hustnn** [comment]
@dcaoyuan 
It seems that already passed this block in Fast sync mode with the latest version.
